### PR TITLE
moving cmake tip

### PR DESCRIPTION
**Pull request by arvsr1988**
putting the build options next to the cmake step where it is so that people can see it earlier and save time .

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by arvsr1988** [comment]
can someone please see this pull request?

**Comment by bisdavid** [comment]
@arvsr1988  Arvind, apologies for the delay.  The original writer for this developer guide left our team some time back, and we've had delays in getting a replacement hired. One is now in place and should be able to get to this soon. We appreciate your patience.  I'll ensure that he sees this PR.  Thanks!

**Comment by SCalwas** [comment]
@arvsr1988 I made some additional changes to the relevant text and merged it all into master. Thanks for your contribution.

**Comment by arvsr1988** [comment]
Wow thanks for the quick response and action. Really appreciate it.

**Pull request merged**
